import { StyleSheet } from "react-native";
import { colors } from "@/theme/colors";
import { spacing } from "@/theme/spacing";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  welcomeText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontWeight: "500",
  },
  userName: {
    fontSize: 26,
    color: colors.text,
    fontWeight: "700",
    marginTop: 4,
  },
  logoutButton: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  logoutText: {
    fontSize: 13,
    color: colors.text,
    fontWeight: "600",
  },
  scrollContainer: {
    paddingBottom: 48,
  },
  balanceCard: {
    marginHorizontal: spacing.lg,
    marginBottom: spacing.lg,
    padding: spacing.lg,
    borderRadius: 16,
    backgroundColor: colors.primary,
  },
  balanceLabel: {
    fontSize: 12,
    color: "rgba(255,255,255,0.72)",
    fontWeight: "600",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  balanceValue: {
    fontSize: 34,
    color: "#FFFFFF",
    fontWeight: "700",
    marginTop: 8,
  },
  balanceCardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 18,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.16)",
  },
  footerLabel: {
    fontSize: 13,
    color: "rgba(255,255,255,0.72)",
  },
  footerValue: {
    fontSize: 13,
    color: "#FFFFFF",
    fontWeight: "600",
  },
  primaryAction: {
    marginHorizontal: spacing.lg,
    marginBottom: spacing.lg,
    backgroundColor: colors.text,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
  },
  primaryActionText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: spacing.lg,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.text,
  },
  sectionAction: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.primary,
  },
  walletList: {
    paddingHorizontal: spacing.lg,
    gap: 10,
    marginBottom: spacing.lg,
  },
  walletRow: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  walletName: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
  },
  walletMeta: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 4,
  },
  walletBalance: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
  },
  emptyHint: {
    marginHorizontal: spacing.lg,
    marginBottom: spacing.lg,
    padding: 16,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  emptyHintText: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  txRow: {
    marginHorizontal: spacing.lg,
    marginBottom: 8,
    padding: 14,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  txTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.text,
  },
  txMeta: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 4,
  },
  txAmountIncome: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.success,
  },
  txAmountExpense: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.danger,
  },
  formContainer: {
    backgroundColor: colors.surface,
    padding: spacing.lg,
    marginHorizontal: spacing.lg,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.lg,
  },
  formTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 16,
  },
  inputGroup: {
    marginBottom: 14,
  },
  inputLabel: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: "600",
    marginBottom: 8,
  },
  input: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: 16,
    color: colors.text,
  },
  typeButtonsContainer: {
    flexDirection: "row",
    gap: 8,
  },
  typeButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.background,
  },
  typeButtonActive: {
    backgroundColor: colors.primaryMuted,
    borderColor: colors.primary,
  },
  typeButtonText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  typeButtonTextActive: {
    color: colors.primary,
  },
  submitButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 8,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  cancelButton: {
    paddingVertical: 12,
    alignItems: "center",
  },
  cancelButtonText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontWeight: "500",
  },
});
